#ifndef COMPONENTS_H
#define COMPONENTS_H


#include "ai/aicomponent.h"
#include "ai/dumbcomponent.h"
#include "base/collidercomponent.h"
#include "base/decaycomponent.h"
#include "base/fsmcomponent.h"
#include "base/predicatecomponent.h"
#include "base/relationshipcomponent.h"
#include "base/spritecomponent.h"
#include "base/tilecomponent.h"
#include "base/timercomponent.h"
#include "base/transformcomponent.h"
#include "effects/bloodpatch.h"
#include "effects/bombruncomponent.h"
#include "effects/camerashakecomponent.h"
#include "effects/firecomponent.h"
#include "effects/shockwavecomponent.h"
#include "effects/soundcomponent.h"
#include "gameplay/damagemodel.h"
#include "gameplay/scorecollector.h"
#include "gameplay/staminacomponent.h"
#include "input/actorcontrollercomponent.h"
#include "input/commandcomponent.h"
#include "input/commandcomponent.h"
#include "input/inputcomponent.h"
#include "spawning/foespawnercomponent.h"
#include "spawning/perkcomponent.h"
#include "spawning/perkspawner.h"
#include "spawning/triggerzonecomponent.h"
#include "ui/overlaycomponent.h"
#include "ui/textcomponent.h"
#include "ui/menucomponent.h"
#include "weapons/grenadecomponent.h"
#include "weapons/projectilecomponent.h"
#include "weapons/weaponbaycomponent.h"

#endif // COMPONENTS_H
