# Generates a C++ translation unit that embeds every file under ASSET_DIR as a
# static byte array, plus a lookup table keyed by the file's path relative to
# PROJECT_ROOT (e.g. "assets/blood.png") so keys match the strings used in code.
#
# Invoked at build time via:
#   cmake -DASSET_DIR=... -DPROJECT_ROOT=... -DOUTPUT_CPP=... -P embed_assets.cmake
#
# The table is exposed through embeddedAssets() declared in engine/resources.h.

if(NOT ASSET_DIR OR NOT PROJECT_ROOT OR NOT OUTPUT_CPP)
    message(FATAL_ERROR "embed_assets.cmake requires ASSET_DIR, PROJECT_ROOT and OUTPUT_CPP")
endif()

# Deterministic, sorted list of asset paths relative to the project root.
file(GLOB_RECURSE asset_files RELATIVE "${PROJECT_ROOT}" "${ASSET_DIR}/*")
list(SORT asset_files)

set(arrays "")
set(entries "")
set(index 0)

foreach(rel ${asset_files})
    file(READ "${PROJECT_ROOT}/${rel}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 2")

    # "ab cd" -> "0xab,0xcd," (trailing comma is legal in an initializer list).
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")

    set(sym "asset_${index}")
    string(APPEND arrays "static const unsigned char ${sym}[] = {${bytes}};\n")
    string(APPEND entries "    { \"${rel}\", { ${sym}, ${size}u } },\n")

    math(EXPR index "${index} + 1")
endforeach()

set(content "// Auto-generated by cmake/embed_assets.cmake. DO NOT EDIT.\n")
string(APPEND content "#include \"engine/resources.h\"\n\n")
string(APPEND content "${arrays}\n")
string(APPEND content "const std::unordered_map<std::string, Resource>& embeddedAssets()\n{\n")
string(APPEND content "    static const std::unordered_map<std::string, Resource> table = {\n")
string(APPEND content "${entries}")
string(APPEND content "    };\n    return table;\n}\n")

# file(WRITE) creates parent directories as needed.
file(WRITE "${OUTPUT_CPP}" "${content}")
